Remove sh dependency.

diff --git a/cmd/csi_driver/Dockerfile b/cmd/csi_driver/Dockerfile
--- a/cmd/csi_driver/Dockerfile
+++ b/cmd/csi_driver/Dockerfile
@@ -50,8 +50,6 @@ FROM distroless-$TARGETARCH AS output-image
 COPY --from=debian /bin/mount /bin/mount
 COPY --from=debian /bin/umount /bin/umount
 COPY --from=debian /bin/mountpoint /bin/mountpoint
-# We should try to remove these
-COPY --from=debian /bin/sh /bin/sh
 COPY --from=debian /bin/cat /bin/cat
 
 # Copy shared libraries into distroless base.
@@ -73,6 +71,7 @@ SHELL ["/bin/bash", "-c"]
 RUN if ldd /bin/mount | grep "not found"; then echo "!!! Missing deps for mount command !!!" && exit 1; fi
 RUN if ldd /bin/umount | grep "not found"; then echo "!!! Missing deps for umount command !!!" && exit 1; fi
 RUN if ldd /bin/mountpoint | grep "not found"; then echo "!!! Missing deps for mountpoint command !!!" && exit 1; fi
+RUN if ldd /bin/cat | grep "not found"; then echo "!!! Missing deps for cat command !!!" && exit 1; fi
 
 # Final build stage, create the real Docker image with ENTRYPOINT
 FROM output-image
